version: "3"
services:
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: osscalendar
      MYSQL_USER: username
      MYSQL_PASSWORD: userpass
      TZ: Asia/Tokyo #`ls -la /etc/localtime | cut -d/ -f8-9
    ports:
      - "3306:3306"
    volumes:
      - ./docker/misc/data:/var/lib/mysql
      - ./docker/misc/conf.d/docker.cnf:/etc/mysql/conf.d/docker.cnf:ro
    container_name: osscal-db

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:cached
      - ./.bash_profile:/root/.bash_profile:ro
      - ./docker/nginx/server.conf://.bash_profile:ro
    links:
      - web
    container_name: osscal-nginx
    environment:
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
      TZ: Asia/Tokyo #`ls -la /etc/localtime | cut -d/ -f8-9

  web:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/html:cached
    links:
      - mysql
      - mailcatcher
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: crmdb
      DATABASE_USER: root
      DATABASE_PASSWORD:
      TZ: Asia/Tokyo #`ls -la /etc/localtime | cut -d/ -f8-9
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhosts
    dns: 8.8.8.8
    container_name: osscal-web

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    container_name: osscal-mc
